data_path: './dataset/webVision/'
dataset: 'WebVision'
num_epochs: 200
num_class: 50 # 15
lr: 2e-2
lr_f: 2e-5
batch_size: 32
warm_up: 15
num_samples: 65944 # 20244
lambda_p: 50

alpha: 0.5
flow_modules: 64-64-64-64
weight_decay: 1e-4
cond_size: 1024  # 384 = 1536 / 4
isRealTask: True
centering: True
center_momentum: 0.9
decay: 0.99

T: 0.5

Tf_warmup: 1.0
Tf: 0.7
flow_sp: False
jumpRestart: True
clip_grad: False

lambda_flow_u_warmup: 0.1
pseudo_std: 0.2
clr_loss: False
